### ISSUE TITLE
Create Data class

### ISSUE THREAD

**Issue by vedangj044** [vedangj044/Frisson#3]
Create data models based on API responses.

**Comment by avinash14022002** [comment]
I like to work this issue...!!!
kindly assign me the issue sir

**Comment by vedangj044** [comment]
You can have a look at the API response on [here](http://azdoktvepqunazyaay.pythonanywhere.com/ufo).

**Comment by codeDamon** [comment]
You @vedangj044 reopened this issue #3, Is there anything left to be solved?

**Comment by vedangj044** [comment]
Yes, we have to create a data class named `UFODataDetail` the response parameter can be found on the api response object at the following link. I think we can make this a subclass of UFOData. Lets see.
You can create this class
[Api response](http://azdoktvepqunazyaay.pythonanywhere.com/ufoid?id=14)

**Comment by spacemonkey1101** [comment]
If this issue is open I would like to work on this if assigned?
