### ISSUE TITLE
arrange code in MVVM pattern

### ISSUE THREAD

**Issue by spacemonkey1101** [vedangj044/Frisson#30]
### I'm submitting a 
- [ ] bug report.
- [ X] feature request.

The code does not follow any architecture but introducing one would be helpful

**Comment by vedangj044** [comment]
Well, I beg to differ here, we are following 100% MVVM architecture, up till now. The business logic, network request are maintained separately, We have maintained a repository class for the paging request. Then we have maintained ViewModel to hold the data, which is then sent to the view.

What you are saying probably is there should be separate packages for each of the file, and I agree with you, you can create separate packages for each.
